services:
  postgres:
    image: postgres:15-alpine
    container_name: lightlink-postgres-container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: lightlink_db
    ports: 
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: